### ISSUE TITLE
Could not call YUICSSOptimizer/ClosureJSOptimizer

### ISSUE THREAD

**Issue by richardcornish** [koenbok/Cactus#103]
When I run `cactus build` or `cactus serve`, I get errors related to my use of optimize in `config.json`:

```
Could not call external processor YUICSSOptimizer: [Errno 2] No such file or directory
Could not call external processor ClosureJSOptimizer: [Errno 2] No such file or directory
```

When I load up a console, importing them like `static/static_optimizers.py` does loads them no problem, so I don't know what I'm doing wrong.

```
>>> from cactus.contrib.external.yui import YUICSSOptimizer`
```

I'm using the v3 branch.

My `config.json`:

```
{
    "fingerprint": [
        "js",
        "css"
    ],
    "optimize": [
        "js",
        "css"
    ],
    "prettify": true
}
```

**Comment by AeonFr** [comment]
Sorry for being so basic, but I have no idea how to install YUI whatsoever, so I looked it in the Ubuntu Software Center and found at leat 4 packages that have "YUI" in the name, but after installing a few the error keeps appearing :/
![yui-what](https://cloud.githubusercontent.com/assets/11742754/11802843/c02a81d6-a2d3-11e5-9dca-09589b4248e7.png)

**Comment by richardcornish** [comment]
YUICSSOptimizer is the name of a Cactus plugin. Under the hood it uses YUI Compressor, which is a Java jar package. The GitHub page is at https://github.com/yui/yuicompressor.

ClosureJSOptimizer is also the name of a Cactus plugin. It uses Google Closure Compiler, which is a also a Java jar package. The GitHub page is at https://github.com/google/closure-compiler.

I have a Mac, and thus use [Homebrew](http://brew.sh/) to make my life easy to install these packages. If you're on Ubuntu, it seems like the best thing to do would be to create your own builds with [Ant](http://ant.apache.org/), which seems to be available as an [Ubuntu package](http://packages.ubuntu.com/wily/ant) (`apt-get install ant`). But first you would need Java on Ubuntu because Ant, YUI Compressor, and Google Closure Compiler all require it as a dependency.

**Comment by AeonFr** [comment]
OK, thanks for the advice.... I've already checked and I do have java in my computer. I didn't knew how to install the pacakges after downloading them, I will check Ant later :+1:
