### ISSUE TITLE
Jinja2 support

### ISSUE THREAD

**Issue by jordancg** [koenbok/Cactus#105]
Any plan to support [jinja2](http://jinja.pocoo.org/) template system?

**Comment by krallin** [comment]
Hard to say. 

Changing template engines would require rewriting the parts that depend on Django (mainly,  `page.py` and `template_tags.py`). However, it'll break existing plugins that rely on Django, so at best we could make this an option.

Providing pluggable template engines (like we have for deployments) might however make sense. Django would be the default, but users would be free to add their own.
