### ISSUE TITLE
easy_install cactus not working

### ISSUE THREAD

**Issue by balachandra** [koenbok/Cactus#110]
Searching for cactus
Reading https://pypi.python.org/simple/cactus/
Download error on https://pypi.python.org/simple/cactus/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'cactus' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or download links found for cactus
error: Could not find suitable distribution for Requirement.parse('cactus')

**Comment by krallin** [comment]
Hey there,

Please consider using pip to install Cactus (`pip install cactus`).

Cheers,
