### ISSUE TITLE
Maintaining Cactus

### ISSUE THREAD

**Issue by 153957** [koenbok/Cactus#111]
On the [Cactus Blog](http://cactusformac.com/blog/) Jorn says:
> The Cactus core is open source, so please keep contributing to the project. We've stopped active development but will maintain the current feature set

I see a lot of open Issues/Pull Requests that have not had answers or follow ups in a while. Are there still some maintainers around to respond to and accept PRs?

**Comment by koenbok** [comment]
I'm around and check once in a while but my priorities are with Framer. @krallin is also an admin but I'm not sure how his workload looks these days.

If someone good is interested to help out let me know.

**Comment by krallin** [comment]
I'm mostly familiar with the 3.x codebase (having worked almost exclusively on that branch), so it's difficult for me to support issues in 2.x (especially considering most of these have been fixed)

If we were to merge 3.x into master (and release it on PyPi), I'll try and make time to go through issues affecting that version.

@koenbok, would that make sense?

**Comment by koenbok** [comment]
Yes making 3.x master is long overdue :-(

I'll try to make some time this week to do that and then we can take it from there ok?

**Comment by krallin** [comment]
Sure, that works for me ; )

@153957 — once we merge 3.x into master, I'll look at the various existing issues and either close them if they were fixed in 3.x, suggest a workaround (if they're feature requests), or look for a fix.

**Comment by stefanooldeman** [comment]
I've been following this repo now for a few days and I'd like to get involved. Some advice would be welcome: on when is a good time to step in (after the 3.x merge to master). And if there are any issues which might be high prio or simple bugs, features to get familiar with. I have prior experiences with python 3, but I see this is a nice opportunity to change that.

**Comment by koenbok** [comment]
After the 3 merge. This weekend :-)

**Comment by koenbok** [comment]
Ok. V3 is now master. 

@krallin go for it and let me know if I can add you to the pypy owners too.
@stefanooldeman now is a good time to step in. My personal request would be to make large projects generate faster. But maybe you should start a bit easier :-)

**Comment by krallin** [comment]
Thanks @koenbok. Being added as a maintainer on PyPi too would be awesome.

@stefanooldeman, I think Python 3 support would be a pretty high priority list item (I was going to try and do some work on this — starting with enabling tests for Python 3), which is now reachable considering that Boto has added support for Python 3. 

Speeding up builds would be a great thing too. I think this would have to be done by tracking dependencies across the objects (pages, static files) we manage, and only re-building what needs to be rebuilt.

Unfortunately, tracking "what has changed" might be difficult, especially once you factor in the effectively unlimited surface area we expose to plugins. Any ideas?

**Comment by krallin** [comment]
Quick update on Py3. I have a branch here that passes the test. I'll publish this in a PR shortly so we can work on it / test it.

Cheers,

**Comment by krallin** [comment]
Hey @koenbok,

Could you add Travis to this repo? The `.travis.yml` file is already here, you just need to register with them and add commit hooks for this repo.

https://travis-ci.org

This will run tests against any PR that is proposed.

**Comment by krallin** [comment]
Started working on a list of the items we want to work on in Cactus here: https://github.com/koenbok/Cactus/issues/117

Feel free to contribute, or even claim an item : )
