### ISSUE TITLE
Is there a way to use global metadata in config.json?

### ISSUE THREAD

**Issue by drevasvoyage** [koenbok/Cactus#125]
What I'd like to do/ am attempting to do is have some form of global metadata in the config.son file:
```
{
    "prettify": true,
    "blog": {
        "id": "fancy-site",
       "author": "Joe Blogs",
      "description": "Such a fancy site"
    }
}
```
And be able to use this in the templates and layouts:

```
<meta name="author" content="{{ blog.author }}">
<meta name="description" content="{{ blog.description }}">

<body id="{{ blog.id }}">
```

Is this currently possible within cactus? The above doesn't work -- how would I go approach implementing global metadata?

Thanks all...

**Comment by krallin** [comment]
Hi there,

Extra context should be included in the `context` key in the configuration:

    {
        "prettify": true,
        "context": {
            "blog": {
                "id": "fancy-site",
                "author": "Joe Blogs",
                "description": "Such a fancy site"
             }
        }
    }

This will be loaded by [the builtin `context` plugin][10]

  [10]: https://github.com/koenbok/Cactus/blob/master/cactus/plugin/builtin/context.py

**Comment by drevasvoyage** [comment]
Massive thanks Krallin.
