### ISSUE TITLE
Unable to deploy to region Frankfurt

### ISSUE THREAD

**Issue by pani-c** [koenbok/Cactus#128]
I am unable to deploy to region Frankfurt (eu-central-1) for several reasons:

1. Not supported authorization mechanism
2. Authorization header is wrong (us-east-1 instead of eu-central-1)

For *1.* I've created a /etc/boto.cfg with `[s3] use-sigv4 = True` as suggested here: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html

For *2.* I've found `"s3-website.eu-central-1.amazonaws.com": "Z21DNDUVLTQW6Q"`and you may want to add that to the domain.py. But I do not know how to tackle the header issue...

**Comment by krallin** [comment]
Hi there,

I've added a new configuration option to support this in S3. The option is called `aws-bucket-region`, just set it to `eu-central-1` and you should be good to go.

I don't think the DNS piece will work just yet, as it seems to not use the methods defined in `s3/engine.py`. I'm not able to fix this just yet as I haven't worked on it before (@koenbok did), but I'll try to do so at some point.

Let me know if this fixes your deployment issue. I'll open a separate issue to track DNS.

Cheers,

**Comment by krallin** [comment]
Two things I forgot to mention:

+ You need to upgrade to `Cactus==3.0.2` to get the fix
+ The website name reported by Cactus will be wrong (it'll report a `us-east-1` URL that won't work) due to a missing constant in Boto. I've opened an issue for this here: https://github.com/boto/boto/pull/3080. 

Cheers,

**Comment by pani-c** [comment]
Thanks, deploying is working now. As stated above the name server stuff and domain:setup isn't.
