### ISSUE TITLE
Output of color codes in Windows results in just control codes

### ISSUE THREAD

**Issue by gregersn** [koenbok/Cactus#148]
Since Windows doesn't support the color codes used by ColorLogger directly, the output contains a lot of garbage.

However, as suggested by the python-colorlog github page: 

> On Windows, requires colorama to work properly. A dependancy on colorama is included as an optional package dependancy - depending on colorlog[windows] instead of colorlog will ensure it is included when installing.

also, by adding

     import colorama

and 

`colorama.init()` at the start of `main()` in `cli.py` output is much more sane.

**Comment by krallin** [comment]
Can you try this branch:

https://github.com/koenbok/Cactus/compare/add-colorama?expand=1

Thanks!

**Comment by gregersn** [comment]
Tested, and it works!

**Comment by krallin** [comment]
Excellent; thanks!
