### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by elguavas** [koenbok/Cactus#158]
i read somewhere in the docs that python 3 is supported, but i had to install cactus in a python 2.x virtualenv to get it to work...

**Comment by elguavas** [comment]
specifically when pip install catcus gets to the stage where it is running:

Running setup.py install for cactus...

there follows lots of syntax errors which would seem to indicate non-python3 compatible code being run.

**Comment by krallin** [comment]
It's in progress, here: https://github.com/koenbok/Cactus/pull/115

Cheers,
