### ISSUE TITLE
jinja2 templates?

### ISSUE THREAD

**Issue by elguavas** [koenbok/Cactus#159]
hi again, last question for now ;) .

it seems sad that cactus pulls in all of (a very old 1.5) version of django just to use the templating engine. is it possible that cactus will eventually support, for example, jinja2 templates, which django itself now officially supports as of version 1.8?

seems like it would be much lighter just to rely on a modern templating engine rather than a (currently ancient) version of django.

just general questions, no expectations. i'm an open source developer myself and i have a full understanding of the time constraints of volunteer developers.

cheers.

**Comment by fedelibre** [comment]
more information on issue #117

**Comment by elguavas** [comment]
ok, thanks for the pointer.  it's interesting that django itself now supports jinja2 templates, i wonder if that makes it any easier to add support to cactus.

**Comment by krallin** [comment]
The main reason for not upgrading to newer Django is Python 2.6 support, which was dropped after Django 1.5.
Cheers,

**Comment by fedelibre** [comment]
@krallin thanks for working on this, I think it's a very desirable feature.
I don't think that anybody care for python 2.6 support.

**Comment by elguavas** [comment]
i agree would be nice, thanks @krallin ;)

**Comment by stefanooldeman** [comment]
:+1: I agree, please consider

**Comment by krallin** [comment]
@fedelibre,

I think it's a bit dangerous to just disregard whomever might be using Python 2.6. Another concern with upgrading is that some plugins might tie into Django internals directly, and those have changed a bit since Django 1.5.

Basically, I have more work to do on identifying what has changed before we can upgrade. 

Cheers,
