### ISSUE TITLE
glue: error: --optipng argument is deprectated since v0.3

### ISSUE THREAD

**Issue by facconi** [koenbok/Cactus#161]
Using Cactus==3.0.2 and glue==0.11.1.
This happens when running cactus build.

**Comment by facconi** [comment]
Using pip install "glue<0.9" fixes temporary the issue.

**Comment by krallin** [comment]
Hey there,

This should not prevent Cactus from properly running (it's just warning). 

Either way, since glue has deprecated that option, I'm removing it from Cactus as well.

Thanks!
