### ISSUE TITLE
cannot insert script before html closing tag

### ISSUE THREAD

**Issue by fedelibre** [koenbok/Cactus#169]
I'm trying to add a script block in a page, just before the closing html tag. The page includes the default base.html template.
I've tried to follow what's done in error.html but it's not working:

```html
{% extends "base.html" %}
{% block body %}
<div class="container">
  <ul id="lightGallery">
  ...
  </ul>
</div>
{% endblock body %}
{% block scripts %}
  <script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
      $("#lightGallery").lightGallery();
    });
  </script>
{% endblock %}
```

**Comment by krallin** [comment]
Do you have a `{% block scripts %}` in  `base.html`?

**Comment by fedelibre** [comment]
yes, just before the closing html tag

**Comment by krallin** [comment]
Can you post the relevant template code?

**Comment by fedelibre** [comment]
I'm not sure what I did wrong before, but it's working fine now.
Sorry for the noise.
