### ISSUE TITLE
default shipped blog.py plugin is using tabs

### ISSUE THREAD

**Issue by samos123** [koenbok/Cactus#174]
Noticed that this file is using tabs instead of 4 spaces: https://github.com/koenbok/Cactus/blob/master/cactus/skeleton/plugins/blog.disabled.py

Is this on purpose? At least it's done consistently in that file but other files seem to use spaces, suggest using 4 spaces.

**Comment by krallin** [comment]
I'm usually against changing indentation for indentation's sake (it makes for noisy commits). However, I'm working on Python 3 support, and Python 3 is less tolerant of mixed use of indentation, so we'll bite the bullet then and update everything to spaces.

In other words; it's coming.

Thanks!
