### ISSUE TITLE
Site list cleared after launching on El Capitan

### ISSUE THREAD

**Issue by mikejohnstn** [koenbok/Cactus#178]
This happened the second time I launched Cactus on El Capitan, and now happens consistently with each launch. My list of sites gets cleared. The "Open Recent" list is also cleared.

I can re-add a site, but it'll be gone next time I launch.

**Comment by jdsimcoe** [comment]
:+1: Also the Preview button has to be clicked twice to load a site.

Further my sites can build and preview from the command line but the built in server doesn't seem to be working in the Cactus app for Mac on El Capitan Public Beta.

**Comment by jdsimcoe** [comment]
@koenbok Any updates on El Cap compatibility for `Cactus.app`?

**Comment by krallin** [comment]
Hi folks, I might have a workaround here: https://github.com/koenbok/Cactus/issues/191 (though I don't have access to the Cactus.app source, so I can't really help there).

Just ping me if that doesn't help and I'll reopen this one

**Comment by jdsimcoe** [comment]
@krallin Beautiful. Works like a champ!
