### ISSUE TITLE
Using Foundation

### ISSUE THREAD

**Issue by stellaxtine** [koenbok/Cactus#192]
Does anyone use Foundation with Cactus? How would I implement it?

**Comment by krallin** [comment]
Assuming you're talking about Zurb Foundation, Cactus really isn't opinionated regarding your choice of CSS framework. To use Foundation, simply add the Foundation CSS files to your project in `static` and change your `base.html` template to load those instead of the bootstrap ones.

**Comment by stellaxtine** [comment]
Sorry, I know you closed this but I'm still having issues with using Foundation in Cactus, though I got it to work. The only problem I have is that I can't get the scss plugin to work. I keep getting this error on build: 
Could not load plugin at path C:\...\saguaro\plugins\scss.py: Couldn't find anything to import: settings
Extensions: <NamespaceAdapterExtension>, <CoreExtension>, <ExtraExtension>, <FontsExtension>, <CompassExtension>, <BootstrapExtension>
Search path:
  C:\...\saguaro
  c:\program files\python 3.5\lib\site-packages\scss\sass\frameworks
on line 1 of 'string:7fb064fc633b2248:@import "settings";\n@import "foundation";'
