### ISSUE TITLE
post.path with pretty urls

### ISSUE THREAD

**Issue by jonsaul** [koenbok/Cactus#218]
HI, looking for an idea on the correct way to work around an issue I have when using the pretty urls and calling <code>/{{ post.path }}</code> my posts are html files and so the resulting url I get back is <code>"/posts/foo.html"</code> which will display <code> "Sorry the page /posts/foo.html could not be found on this server."</code>

So essentially my issue is that in a page called "posts.html" (rendered url is /posts/) I am doing something like:

```{% for post in posts  %} <a href="/{{ post.path }}">{{post.title}}</a> {% endfor %}```

and getting the message 
<code> "Sorry the page /posts/foo.html could not be found on this server."</code>

Any ideas on how I dynamically pull the post.path to return something more like <code>/posts/foo/</code>, if I manually remove <code>.html</code> from the url the page will render correctly.

Hopefully this isn't a stupid question...

**Comment by krallin** [comment]
No, definitely not a stupid question :). 

This is actually supported out of the box:

````
<a href="{% url  post.path %}">{{ post.title }}</a>
```

Then, enable `prettify` in your configuration (see the [README](https://github.com/koenbok/Cactus#pretty-urls))

Cheers,

**Comment by jonsaul** [comment]
Hi thanks for your quick response on this: your answer makes perfect sense to me and I have been through the steps your suggested, I am still experiencing some issues with this, in order to test I cloned the example blog from github and tried to use this method on there , I can see that in the build folder the posts are now moved into a directory and an 'index.html' has been created for each, I still get the same response though when I attempt to link to a post using <code>{% url post.path %}</code> this makes me think I am missing some additional config setting maybe, the url still returns the post with the html extension and is not found <code>Sorry the page /posts/third-post.html could not be found on this server.</code> for example...

**Comment by jonsaul** [comment]
also getting this output to the console during build 

<code>/index.html: static resource does not exist: static/css/master.css
/index.html: page resource does not exist: posts/third-post.html
/index.html: page resource does not exist: posts/second-post.html
/index.html: page resource does not exist: posts/first-post.html
/posts/first-post.html: static resource does not exist: favicon.ico
/posts/first-post.html: static resource does not exist: static/css/master.css
/posts/first-post.html: page resource does not exist: posts/second-post.html
/posts/second-post.html: static resource does not exist: favicon.ico
/posts/second-post.html: static resource does not exist: static/css/master.css
/posts/second-post.html: page resource does not exist: posts/first-post.html
/posts/second-post.html: page resource does not exist: posts/third-post.html
/posts/third-post.html: static resource does not exist: favicon.ico
/posts/third-post.html: static resource does not exist: static/css/master.css
/posts/third-post.html: page resource does not exist: posts/second-post.html</code>

**Comment by krallin** [comment]
Duh. That blog plugin is a mess : (...

All right, here's what you should do:

+ In `plugins/blog.py`, add `postContext['page'] = page` below all the other `postContext['page]' = ...` statements
+ In the page, use this:

{% for post in posts %}
    <a href="{% url  post.page.link_url %}">{{ post.title }}</a>
{% endfor %}

Cheers,

**Comment by jonsaul** [comment]
Amazing, working perfectly now. Thank you so much :)

**Comment by krallin** [comment]
Awesome; happy to help : )
