### ISSUE TITLE
Fingerprinted files are not removed on build

### ISSUE THREAD

**Issue by pani-c** [koenbok/Cactus#222]
Building or serving a site with fingerprinting enabled for css and js files leads to a growing number of css and js files.

Each time a css or js file gets edited it gets added to the build folder with a new fingerprint, which is fine. But the old files are also kept in the build folder.

I'd expected to see some kind of "compare fingerprint and if it differs replace the file" behavior. Or at least always replace the fingerprinted files wether they were edited or not...

**Comment by krallin** [comment]
In this case it might make sense just to clean out your `.build` directory. is that problematic for you? 

Not sure I understood your last sentence about replacing the fingerprinted files.  Let me know if you can clarify. 

Cheers,

**Comment by pani-c** [comment]
Cleaning the .build directory would make sense. Where would I need to add the *remove* code?

Regarding the last sentences:
I expected only the files that changed get overwritten on build, not all of them (coming from HUGO I was used to this). Just noticed every file gets rewritten on build. Thats fine, I just need to get rid of the not needed files for my automated deploying.

**Comment by pani-c** [comment]
I just added `site.clean()` to the build function in the *cli.py* for now...

**Comment by dennisblume** [comment]
@pani-c I ran into the same issue, I was thinking maybe you would like to use a plugin instead of modifying the the core. I attached the one I am using below :smile: 
[clear_before_build.py.zip](https://github.com/koenbok/Cactus/files/84092/clear_before_build.py.zip)

**Comment by pani-c** [comment]
@dennisblume thanks for the plugin. Much cleaner solution! Hacking the core was really just a quick fix...
