### ISSUE TITLE
Deployment to AppEngine?

### ISSUE THREAD

**Issue by Offbeatmammal** [koenbok/Cactus#33]
no offence to S3 but with the free threshold on AppEngine it would be great to have an option to deploy to there rather than S3. I'll admit to not having spent much time with Cactus yet so not sure how big a job it would be, but just something to consider.

**Comment by krallin** [comment]
Deployment engines are pluggable in V3 (and there are examples besides S3). We have GCS and Rackspace. Will close this for now (old issue, etc.).
