### ISSUE TITLE
Keychain mangement fails on Linux

### ISSUE THREAD

**Issue by pablohoffman** [koenbok/Cactus#36]
`cactus deploy` works but gives the following error on Linux (and fails to store AWS private key):

    sh: 1: security: not found

It's a shame to have this simple issue because all the rest works flawlessly.

I see it's because Cactus assumes it's running on Mac and uses OS X `security` command to store the password. Could we release this assumption (checking `sys.platform` or something). Also, why not support keeping the private key on `config.json`? Is it because of some security policy?.  It could also be handy to support the standard environment variables (ie. `AWS_SECRET_ACCESS_KEY`) which boto does by default, but that behavior is overridden.

**Comment by krallin** [comment]
Hey there,

This should be fixed in Cactus v3. Let us know if that's still an issue for you.

Cheers,

**Comment by joshuakarjala** [comment]
Cactus still doesn't pick up `AWS_SECRET_ACCESS_KEY` even though it's set in the environemnt
