### ISSUE TITLE
internationalisation

### ISSUE THREAD

**Issue by spacedman** [koenbok/Cactus#7]
Feature request: use the django translation mechanisms, via the {% trans %} tag and friends, to create multilingual sites.

Need to specify which languages, and where to create the built sites (eg build/en/ and build/fr/ perhaps?).

Should be as simple as (ha!) looping over the languages, setting the language, and rendering the pages into the right location.

That should cover html, not sure about Javascript...

**Comment by rryan** [comment]
I just generated a PO file with ```cactus messages:make``` and Django template translation tools so I'm pretty sure this is fixed :).

**Comment by krallin** [comment]
Haha, it was indeed fix a while back : )

Cheers,
