### ISSUE TITLE
Broken Pipe Error with boto.connect_s3 and host='s3.amazonaws.com' for non-default AWS region

### ISSUE THREAD

**Issue by amsb** [koenbok/Cactus#86]
I'm unable to deploy to S3 on us-west-2 because boto.connect_s3 in deployment/s3/engine.py explicitly sets host to s3.amazonaws.com which causes Broken Pipe Errors. Leaving host unset in this call solves the problem (by presumably letting boto auto-set the correct host), at least for boto 2.28.0 on my system. See related at https://github.com/boto/boto/issues/621

**Comment by SohailKh** [comment]
try removing your bucket policy under permissions in bucket properties.

**Comment by jakealstad** [comment]
I am still having this exact issue. The deployment always hangs on a file and eventually times out.

<img width="370" alt="screen shot 2015-07-08 at 10 32 20 am" src="https://cloud.githubusercontent.com/assets/625776/8577312/b4a9cb72-255c-11e5-9bbf-de3674ef1c10.png">
