### ISSUE TITLE
Where is config.json?

### ISSUE THREAD

**Issue by dangayle** [koenbok/Cactus#90]
In the docs you mention a config.json file, but when I `cactus create <foo>`, there is no config file created. Where does it go?

**Comment by qaidj** [comment]
Thanks @krallin for helping to maintain the project. I was getting into Catus v2; now excited to make Cactus v3 work for me as well.

Sorry to seem daft, but using v3, if I use the CLI try to point Cactus to the config file in the root of a newly created project:

`cactus -c config.json`

I get the `cactus: error: invalid choice` error. All other actions are not possible until I get my config in place.

Any advice? Thanks in advance.

**Comment by krallin** [comment]
Hey @qaidj,

Does `cactus -c config.json  build` work? 

I can see that adding a "config-check"  command might be useful though. Is that what you're after?

Cheers,

**Comment by qaidj** [comment]
Hmm .. no dice. Tried it and get the same `error: invalid choice`

Since the engine requires a config file, I have created one, but I can't get Cactus to recognize it. What would "config-check" do? Confirm format / existence?

**Comment by krallin** [comment]
Well, I'm not actually sure of what you're trying to achieve here: you're running Cactus without a command, so it tells you you need a command.

I'm sure you actually intend to do something else, but what is that?

(Sorry, the command above probably should have been `cactus build -c config.json` — if that still doesnt work, can you paste the CLI output and run `cactus --help` for me?). 

Cheers,

**Comment by qaidj** [comment]
Ah - it was indeed `cactus build -c config.json` that works.

Thanks for that!

(Just for clarity, I wasn't able to run `cactus serve` or `cactus build`, etc. without having a config file pointed to, so I was stuck there.)

**Comment by krallin** [comment]
What error did you get without a config file? Was that a bug?

I'll try and check whether we can accept `-c` regardless of where it is

Cheers,

**Comment by qaidj** [comment]
I don't know enough about the way Cactus is supposed to give feedback to say it was a bug, but here are the details of what I tried:

- My first step was to create a new project with the command `cactus create path-name/`. This was successful.
- When trying to start up the server with `cactus serve`, I got the warning line `Unable to load configuration at config.json` followed by

```
Running webserver at http://127.0.0.1:8000 for /Users/me/my-junk/.build  
Type control-c to exit
```

I was able to access the project at this local URL. But was still getting the warning after save.

- When trying to run the build process with `cactus build` I got the same warning line `Unable to load configuration at config.json`
- I created the config.json file and put the `{"prettify": true}` in there and tried `cactus serve` again, but got the same message as before. I searched a bit and saw this thread so I tried `cactus -c config.json` which yielded this response:    

```
usage: cactus [-h]

              {messages:make,deploy,create,serve,domain:list,build,domain:setup}
              ...
cactus: error: invalid choice: 'config.json' (choose from 'messages:make', 'deploy', 'create', 'serve', 'domain:list', 'build', 'domain:setup')
```

- Then I tried your first suggestion (`cactus -c config.json build`) and got the same above error. Your subsequent reply with the `cactus build -c config.json` suggestion did the trick and I was able to move on.

**Comment by krallin** [comment]
Thanks for those details, @qaidj,

The error you were seeing was actually just a warning, but I can see how you'd think otherwise. I'll try and make this whole thing a little bit less confusing.

Cheers,

**Comment by qaidj** [comment]
Good point - warnings, not errors.

Knowing that the full command of `cactus build -c config.json` was required was the only thing I needed.

**Comment by thesues** [comment]
Do you have an example file for config.json? I do not know where to put my aws key

**Comment by krallin** [comment]
@thesues ,

You can run `cactus deploy` without passing a config file and Cactus will:

+ Prompt you for configuration it needs
+ Create the config file for you

Cheers,

**Comment by fedelibre** [comment]
`cactus deploy` is going to work only if you have an AWS account, otherwise it will break when you just hit enter when Amazon keys are asked. The error is `cactus.exceptions.InvalidCredentials`.

Back to the original question, I cannot make it work. I'm using version 3.02 installed from PyPI.
Whatever I write in config.json is ignored (links are not prettified) and I keep getting the same warning:

```
$ cactus serve -c config.json 
Unable to load configuration at config.json
Running webserver at http://127.0.0.1:8000 for /home/fede/web/cactus/sixbarsjail.it/.build
Type control-c to exit
```

This is my config.json, at the root of the project:

```
{
  "site-url": "http://example.com/",
  "prettify": true,
}
```

**Comment by krallin** [comment]
@fedelibre ,

1. I didn't understand your point regarding having an AWS account. Can you clarify? Did you mean you're trying to deploy to another provider and Cactus isn't prompting you for that? 

2. Your `config.json` is not valid JSON. There's a trailing comma. That's why it's not being loaded. IIRC we fixed that in master (the error is clearer now) but it might not be in the PyPi version yet (I have a small list of other fixes I'd like to make before pushing a new version).

Cheers,

**Comment by fedelibre** [comment]
I just pip installed from master.

1. Well, I don't have an AWS account and AWS seems the only provider supported by cactus deploy. I hoped that `cactus deploy` could be used to generate a valid config.json and could ignore an empty value for AWS keys. It would be nice if it supported webfaction or, better, ssh configuration.

2. Right, I don't know JSON. I just installed jsonlint (provided by python-demjson in debian). I should have removed the trailing comma after `true`.

BTW, the option -c is not documented in the help.. but it's also not needed, as cactus is able to find the config.json file (at least if in the root of the project).

**Comment by krallin** [comment]
Hey @fedelibre 

You can actually set `"provider"` in your configuration to use one of the other supported deployment engines, which currently include `"aws"` (S3), `"rackspace"` (cloud files) and `"google"` (GCS). 

Adding other providers is rather simple, but so far no one has worked on Webfaction or (s)ftp.

Cheers,

**Comment by charliesneath** [comment]
@krallin Thanks for the help in this thread. Agreeing with @dangayle that the language in the help doc is confusing as it implies `config.json` already exists, when it in fact needs to be created.

I am happy to update the language of the `README.md` so that it's more clear that `config.json` needs to be user generated.

Is there a reason that it can't be automatically created when the project is created?

**Comment by krallin** [comment]
@charliesneath I agree. Perhaps adding a default `config.json` is the right approach. That should be reasonably straightforward.

**Comment by krallin** [comment]
I've included a default `config.json` in the skeleton in https://github.com/koenbok/Cactus/commit/afa9bad5bbf556f6ce95c8f4d50c9e3ad1318aa9 — thanks for the suggestion!

**Comment by charliesneath** [comment]
@krallin Great, thank you!
